version: '2'

services:
  mini-yelp-api:
    build:
      context: .
    volumes:
      # Mounts the project directory on the host to /app inside the container,
      # allowing you to modify the code without having to rebuild the image.
      - .:/app
      # Just specify a path and let the Engine create a volume.
      # Data present in the base image at the specified mount point will be copied
      # over to the new volume upon volume initialization.
      # node_modules from this new volume will be used and not from your local dev env.
      - /app/node_modules/
    ports:
      - "4040:4040"
    env_file:
      - .env
    links:
      - mongo
  mongo:
    image: "mongo:3.4"
    ports:
      - "27017:27017"
